language: go
sudo: false
go:
  - tip
before_install:
  - go get code.google.com/p/go.tools/cmd/cover 
  - go get github.com/mattn/goveralls 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/dep/cmd/dep
install:
  - $GOPATH/bin/dep ensure -v
script:
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -L 1 sh -c
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci 