// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/flaki-service/pkg/flaki (interfaces: Component)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	fb "github.com/cloudtrust/flaki-service/api/fb"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Component is a mock of Component interface
type Component struct {
	ctrl     *gomock.Controller
	recorder *ComponentMockRecorder
}

// ComponentMockRecorder is the mock recorder for Component
type ComponentMockRecorder struct {
	mock *Component
}

// NewComponent creates a new mock instance
func NewComponent(ctrl *gomock.Controller) *Component {
	mock := &Component{ctrl: ctrl}
	mock.recorder = &ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Component) EXPECT() *ComponentMockRecorder {
	return m.recorder
}

// NextID mocks base method
func (m *Component) NextID(arg0 context.Context, arg1 *fb.FlakiRequest) (*fb.FlakiReply, error) {
	ret := m.ctrl.Call(m, "NextID", arg0, arg1)
	ret0, _ := ret[0].(*fb.FlakiReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextID indicates an expected call of NextID
func (mr *ComponentMockRecorder) NextID(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextID", reflect.TypeOf((*Component)(nil).NextID), arg0, arg1)
}

// NextValidID mocks base method
func (m *Component) NextValidID(arg0 context.Context, arg1 *fb.FlakiRequest) *fb.FlakiReply {
	ret := m.ctrl.Call(m, "NextValidID", arg0, arg1)
	ret0, _ := ret[0].(*fb.FlakiReply)
	return ret0
}

// NextValidID indicates an expected call of NextValidID
func (mr *ComponentMockRecorder) NextValidID(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextValidID", reflect.TypeOf((*Component)(nil).NextValidID), arg0, arg1)
}
