// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/flaki-service/pkg/flaki (interfaces: Flaki)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// Flaki is a mock of Flaki interface
type Flaki struct {
	ctrl     *gomock.Controller
	recorder *FlakiMockRecorder
}

// FlakiMockRecorder is the mock recorder for Flaki
type FlakiMockRecorder struct {
	mock *Flaki
}

// NewFlaki creates a new mock instance
func NewFlaki(ctrl *gomock.Controller) *Flaki {
	mock := &Flaki{ctrl: ctrl}
	mock.recorder = &FlakiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *Flaki) EXPECT() *FlakiMockRecorder {
	return m.recorder
}

// NextIDString mocks base method
func (m *Flaki) NextIDString() (string, error) {
	ret := m.ctrl.Call(m, "NextIDString")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextIDString indicates an expected call of NextIDString
func (mr *FlakiMockRecorder) NextIDString() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextIDString", reflect.TypeOf((*Flaki)(nil).NextIDString))
}

// NextValidIDString mocks base method
func (m *Flaki) NextValidIDString() string {
	ret := m.ctrl.Call(m, "NextValidIDString")
	ret0, _ := ret[0].(string)
	return ret0
}

// NextValidIDString indicates an expected call of NextValidIDString
func (mr *FlakiMockRecorder) NextValidIDString() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextValidIDString", reflect.TypeOf((*Flaki)(nil).NextValidIDString))
}
